import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CookiesWrapper from "@/providers/CookiesWrapper";
import Panel from "@/components/Panel";
import LayoutContainer from "@/components/LayoutContainer";
import QueryWrapper from "@/providers/QueryWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable}antialiased`}
      >
        <CookiesWrapper>
          <QueryWrapper>
            <LayoutContainer>
              {children}
            </LayoutContainer>
          </QueryWrapper>
        </CookiesWrapper>
      </body>
    </html>
  );
}
